name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.0
        with:
          version: 6

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm lint:format

      - name: Check types
        run: pnpm lint:types
